### ISSUE TITLE
Instructor Feedback -Week 1 Deliverables

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [EntJavaTeamProj/TeamProjOnline#2]
@ScarletIvy @AshleyNWagner @eburzlaff @Mlor10 

- [ ] Team Charter and Resume - complete. One thing to consider and perhaps document is your git strategy. For example: will you use feature branches, developer branches, pull requests?

- [ ] Scope - to help me understand the scope of your application, can you share what resources your service will provide, the attributes of those resources, and the https verbs supported? Example: For a service that focused on Vehicle data, that might include:

- a Vehicle resource with make, model, year, vehicle id number (vin), color, safety rating, etc.
- operations might include get by vin, get by make, get by model, get by year, delete by id, etc.

**Comment by Mlor10** [comment]
@pawaitemadisoncollege 
We are going to be using feature branches such as an api branch to develop on instead of developing on the main branch. 

For the scope, we plan on combining the the properties of two apis of the same name search into one object and convert it back into json as a response with the endpoint being the name. We had planned on using a tcg api for market prices of the cards, but the estimation time before receiving the api developer key to gain access to the api information is several weeks from now. We decided to instead use an api that retrieves digimon information and image based off of the entire franchise to go along with the digimon io card api. So users will be able to search up a card and get information such as cardname, cardnumber, etc then along with its digimon api properties such as the image and level (which is the evolution stage of the digimon).

**Comment by pawaitemadisoncollege** [comment]
@Mlor10 @ScarletIvy @AshleyNWagner @eburzlaff Glad to hear you are on track with the api. Be sure to document the resources, resource fields/properties, operations and response types (json, xml, plaintext, etc) so everyone looking at the repository understands the scope - the readme.md is a good place for this.
